/** Shared tokenization. Stopword removal keeps the MOCK embedder and the
 * lexical (hybrid) scorer focused on content words, so similarity reflects
 * topic overlap rather than shared function words. Real OpenAI embeddings don't
 * need this — it only sharpens the offline stand-in and the lexical signal.
 */
// Content tokens: alphanumeric runs that keep internal . _ - so version strings
// and identifiers survive whole (e.g. "v2.3", "sdk-v4", "e_42") — that's exactly
// what lets the lexical (hybrid) scorer match the exact tokens embeddings miss.
const WORD_RE = /[a-z0-9]+(?:[._-][a-z0-9]+)*/g;

const STOPWORDS = new Set<string>([
  "a",
  "an",
  "the",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "to",
  "of",
  "in",
  "on",
  "for",
  "and",
  "or",
  "do",
  "does",
  "did",
  "done",
  "how",
  "what",
  "when",
  "where",
  "who",
  "whom",
  "why",
  "which",
  "can",
  "could",
  "should",
  "would",
  "will",
  "shall",
  "may",
  "might",
  "i",
  "you",
  "he",
  "she",
  "it",
  "we",
  "they",
  "my",
  "me",
  "your",
  "our",
  "this",
  "that",
  "these",
  "those",
  "with",
  "at",
  "as",
  "from",
  "by",
  "but",
  "not",
  "no",
  "yes",
  "please",
  "since",
  "there",
  "here",
  "any",
  "if",
  "so",
  "up",
  "out",
  "about",
  "into",
  "over",
  "than",
  "then",
]);

export function tokenize(text: string): string[] {
  return [...(text.toLowerCase().match(WORD_RE) ?? [])].filter((t) => !STOPWORDS.has(t));
}
